name       : lsd
version    : 0.18.0
release    : 2
source     :
    - https://github.com/Peltoche/lsd/archive/0.18.0.tar.gz : 2905e5d8d61d98d60c65544f3d41ae77459c8a92a4c7acafadcfb0233b2b7f95
homepage   : https://github.com/Peltoche/lsd
license    : Apache-2.0
component  : system.utils
summary    : The next generation ls command
description: |
    The next generation ls command with a lot of pretty colors and icons.
networking : yes
builddeps  :
    - cargo
rundeps    :
    - font-awesome-4
    - font-awesome-ttf
build      : |
    cargo build %JOBS% --release
install    : |
    cargo install %JOBS% lsd --root=$installdir/usr
    rm -f $installdir/usr/.crates*
