name       : lsd
version    : 0.22.0
release    : 9
source     :
    - https://github.com/Peltoche/lsd/archive/refs/tags/0.22.0.tar.gz : 30ad1b1d014c7b6a2fca44c6de3b17198c84168d34fc946245d67094ebc0f7ed
homepage   : https://github.com/Peltoche/lsd
license    : Apache-2.0
component  : system.utils
summary    : The next generation ls command
description: |
    The next generation ls command with a lot of pretty colors and icons.
networking : yes
builddeps  :
    - cargo
rundeps    :
    - font-awesome-ttf
build      : |
    export SHELL_COMPLETIONS_DIR=completions
    cargo build %JOBS% --release
install    : |
    cargo install %JOBS% lsd --root=$installdir/usr
    rm -f $installdir/usr/.crates*

    install -Dm00644 completions/_lsd $installdir/usr/share/zsh/site-functions/_lsd
    install -Dm00644 completions/lsd.bash $installdir/usr/share/bash-completion/completions/lsd
    install -Dm00644 completions/lsd.fish $installdir/usr/share/fish/vendor_completions.d/lsd.fish
check      : |
    cargo test
