name       : lsd
version    : 0.20.1
release    : 5
source     :
    - https://github.com/Peltoche/lsd/archive/0.20.1.tar.gz : a2086aa049b8bd21c880f23b21b0e9ef21d3c3829d40641aa8810c08be936c19
homepage   : https://github.com/Peltoche/lsd
license    : Apache-2.0
component  : system.utils
summary    : The next generation ls command
description: |
    The next generation ls command with a lot of pretty colors and icons.
networking : yes
builddeps  :
    - cargo
rundeps    :
    - font-awesome-4
    - font-awesome-ttf
build      : |
    export SHELL_COMPLETIONS_DIR=completions
    cargo build %JOBS% --release
install    : |
    cargo install %JOBS% lsd --root=$installdir/usr
    rm -f $installdir/usr/.crates*

    install -Dm00644 completions/_lsd $installdir/usr/share/zsh/site-functions/_lsd
    install -Dm00644 completions/lsd.bash $installdir/usr/share/bash-completion/completions/lsd
    install -Dm00644 completions/lsd.fish $installdir/usr/share/fish/vendor_completions.d/lsd.fish
check      : |
    cargo test
