name       : lsd
version    : 0.17.0
release    : 1
source     :
    - https://github.com/Peltoche/lsd/archive/0.17.0.tar.gz : 65b03ae322c4d3ed47f502866b4da2b2c7029b6cb5dc989e98664d564a57de1d
homepage   : https://github.com/Peltoche/lsd
license    : Apache-2.0
component  : system.utils
summary    : The next generation ls command
description: |
    The next generation ls command with a lot of pretty colors and icons.
networking : yes
builddeps  :
    - cargo
rundeps    :
    - font-awesome-4
    - font-awesome-ttf
build      : |
    cargo build %JOBS% --release
install    : |
    cargo install %JOBS% lsd --root=$installdir/usr
    rm -f $installdir/usr/.crates*
