name       : lsd
version    : 1.0.0
release    : 11
source     :
    - https://github.com/lsd-rs/lsd/archive/refs/tags/v1.0.0.tar.gz : ab34e9c85bc77cfa42b43bfb54414200433a37419f3b1947d0e8cfbb4b7a6325
homepage   : https://github.com/Peltoche/lsd
license    : Apache-2.0
component  : system.utils
summary    : The next generation ls command
description: |
    The next generation ls command with a lot of pretty colors and icons.
networking : yes
builddeps  :
    - cargo
rundeps    :
    - font-awesome-ttf
build      : |
    export SHELL_COMPLETIONS_DIR=completions
    cargo build %JOBS% --release
install    : |
    cargo install %JOBS% lsd --root=$installdir/usr
    rm -f $installdir/usr/.crates*

    install -Dm00644 completions/_lsd $installdir/usr/share/zsh/site-functions/_lsd
    install -Dm00644 completions/lsd.bash $installdir/usr/share/bash-completion/completions/lsd
    install -Dm00644 completions/lsd.fish $installdir/usr/share/fish/vendor_completions.d/lsd.fish
#check      : |
#    cargo test
